### ISSUE TITLE
Error when running python-to-rust

### ISSUE THREAD

**Issue by andygoldschmidt** [alexcrichton/rust-ffi-examples#4]
When running the `Makefile` in `python-to-rust`, I get the following error:

```
▶ make
cargo build
   Compiling python-to-rust v0.1.0 (file:///Users/andy/Documents/playground/rust-ffi-examples/python-to-rust)
(cd target && ln -nsf debug/libdouble_input-*dylib libdouble_input.so)
python src/main.py
Traceback (most recent call last):
  File "src/main.py", line 3, in <module>
    lib = cdll.LoadLibrary('target/libdouble_input.so')
  File "/Users/andy/miniconda/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/Users/andy/miniconda/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(target/libdouble_input.so, 6): image not found
make: *** [all] Error 1
```

This happens for Python 2.7 as well as 3.4 with Rust 1.0

Any ideas? :)

**Comment by alexcrichton** [comment]
Oh thanks for the update! I've pushed a few build fixes for Cargo changes, so it should be working out now!

**Comment by andygoldschmidt** [comment]
Thanks for the speedy fix, works fine now!
